enum VpnSessionStatus {
  NONE
  CONNECTED
  DISCONNECTED
  EXPIRED
}

type VpnSession {
  id: String!
  status: VpnSessionStatus!
}

type Mutation {
  createSession: VpnSessionStatus!
  deleteSession: VpnSessionStatus!
}

extend type Subscription {
  vpn: VpnSession!
}
