enum ErrorType {
  NONE = 'NONE',

  /**
   * Request
   */
  EXPRESS_MIDDLEWARE = 'EXPRESS_MIDDLEWARE',
  WEBSOCKET_CONNECTION_PARAMS = 'WEBSOCKET_CONNECTION_PARAMS',

  /**
   * Auth JOSE
   */
  AUTH_CONSTRUCTOR = 'AUTH_CONSTRUCTOR',
  AUTH_KEY = 'AUTH_KEY',
  AUTH_JSON_WEB_KEY_STORE = 'AUTH_WEB_KEY_CLIENT',

  /**
   * Auth Handshake
   */
  AUTH_NO_SECRET_OR_PUBLIC_KEY_FOUND = 'AUTH_NO_SECRET_OR_PUBLIC_KEY_FOUND',
  AUTH_NO_SECRET_FOUND = 'AUTH_NO_SECRET_FOUND',
  AUTH_HEADER_NOT_FOUND = 'AUTH_HEADER_NOT_FOUND',
  AUTH_HEADER_MALFORMED = 'AUTH_HEADER_MALFORMED',
  AUTH_AUTH_TYPE_INVALID = 'AUTH_AUTH_TYPE_INVALID',
  AUTH_FAILED_TO_DECODE_TOKEN = 'AUTH_FAILED_TO_DECODE_TOKEN',
  AUTH_TOKEN_VERIFICATION_FAILED = 'AUTH_TOKEN_VERIFICATION_FAILED',
  AUTH_PUBLIC_KEY_FETCH_FAILED = 'AUTH_PUBLIC_KEY_FETCH_FAILED',
  AUTH_PUBLIC_KEY_HAS_NO_SECRET = 'AUTH_PUBLIC_KEY_HAS_NO_SECRET',
}

export { ErrorType }
