enum AuthError {
  NONE = 'NONE',
  AUTHORIZATION_NO_SECRET_OR_PUBLIC_KEY_FOUND = 'AUTHORIZATION_NO_SECRET_OR_PUBLIC_KEY_FOUND',
  AUTHORIZATION_NO_SECRET_FOUND = 'AUTHORIZATION_NO_SECRET_FOUND',
  AUTHORIZATION_HEADER_NOT_FOUND = 'AUTHORIZATION_HEADER_NOT_FOUND',
  AUTHORIZATION_HEADER_MALFORMED = 'AUTHORIZATION_HEADER_MALFORMED',
  AUTHORIZATION_AUTH_TYPE_INVALID = 'AUTHORIZATION_AUTH_TYPE_INVALID',
  AUTHORIZATION_FAILED_TO_DECODE_TOKEN = 'AUTHORIZATION_FAILED_TO_DECODE_TOKEN',
  AUTHORIZATION_TOKEN_VERIFICATION_FAILED = 'AUTHORIZATION_TOKEN_VERIFICATION_FAILED',
  AUTHORIZATION_PUBLIC_KEY_FETCH_FAILED = 'AUTHORIZATION_PUBLIC_KEY_FETCH_FAILED',
  AUTHORIZATION_PUBLIC_KEY_HAS_NO_SECRET = 'AUTHORIZATION_PUBLIC_KEY_HAS_NO_SECRET',
}

export { AuthError }
