name: Test Builds

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install node
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: serve
        run: |
          npm run serve &
          curl 'http://localhost:4000' \
            -H 'content-type: application/json' \
            --retry 2 \
            --retry-delay 1 \
            --data-binary '{"operationName":"test","variables":{},"query":"query test {\n  ping\n}\n"}' \
            --compressed
